const BRAND = {
  dark: "#1b2126",
  accent: "#e63329",
  light: "#f5f5f5",
  mid: "#e8e8e8",
  text: "#1b2126",
  white: "#ffffff",
};

const slides = [
  {
    id: 1, type: "title",
    title: "RecXpress SFTP Setup",
    subtitle: "A Guide for Business Partners",
    clientTitle: "Automatic Bank Statement Retrieval",
    clientSubtitle: "How RecXpress connects securely to your bank",
    notes: "Welcome slide — introduce the topic of SFTP setup within RecXpress for automated bank statement retrieval.",
  },
  {
    id: 2, type: "bullets", icon: "🔒",
    title: "What is SFTP in RecXpress?",
    clientTitle: "What Does This Do For You?",
    points: [
      "SFTP stands for Secure File Transfer Protocol",
      "Enables RecXpress to automatically retrieve bank statements from your bank's SFTP server",
      "Eliminates the need to manually download and import statement files",
      "Configured per bank account inside Sage 300 Cashbook Bank Account setup",
    ],
    clientPoints: [
      "Your bank statements are collected automatically — no manual downloads needed",
      "Statements flow directly into Sage 300 for reconciliation",
      "Saves time and reduces the risk of missing or incorrect imports",
      "Each bank account is configured separately so every account is covered",
    ],
    notes: "Set the scene — SFTP automates statement collection. Stress the per bank nature of setup.",
  },
  {
    id: 3, type: "steps",
    title: "Where to Find the Setup",
    clientTitle: "Getting Started in Sage 300",
    steps: [
      { step: "1", label: "Log in to Sage 300" },
      { step: "2", label: "Go to Cashbook > C/B Setup > Bank Accounts" },
      { step: "3", label: "Open the relevant Bank Account" },
      { step: "4", label: "Click the RecXpress tab" },
      { step: "5", label: "Select your Retrieve Statement Method from the dropdown" },
    ],
    notes: "Walk partners through the navigation path. The RecXpress tab is specifically for SFTP setup.",
  },
  {
    id: 4, type: "methods",
    title: "Retrieve Statement Methods",
    clientTitle: "How Would You Like to Connect?",
    methods: [
      { name: "Local", icon: "💻", desc: "File downloaded manually to a local or network folder", clientDesc: "You download the file yourself and point RecXpress to it" },
      { name: "Sage Bank Feeds", icon: "🏦", desc: "Automatic live feed — connects directly to your bank (OnPremise only)", clientDesc: "Live connection to your bank — fully automatic (OnPremise only)" },
      { name: "SFTP with Password", icon: "🔑", desc: "Securely transfer using a username and password", clientDesc: "Secure automatic download using your bank-provided login" },
      { name: "SFTP with Key File", icon: "🗝️", desc: "Enhanced security using cryptographic keys instead of passwords", clientDesc: "Higher security option using an encrypted key file" },
      { name: "SFTP 2FA", icon: "🛡️", desc: "Two-factor authentication — highest security level", clientDesc: "Maximum security with two-step verification" },
    ],
    notes: "Most clients using automated retrieval will use SFTP with Password or Key File.",
  },
  {
    id: 5, type: "table",
    title: "SFTP Setup Fields Explained",
    clientTitle: "Information You Will Need From Your Bank",
    rows: [
      { field: "Host IP Address", value: "IP address or hostname of the bank's SFTP server", clientValue: "Provided by your bank — the address of their secure file server" },
      { field: "User", value: "Login username provided by the bank", clientValue: "Your SFTP username, provided by your bank" },
      { field: "User Password", value: "Password for the SFTP user (Password method only)", clientValue: "Your SFTP password, provided by your bank" },
      { field: "Key File Path", value: "Path to private key e.g. C:\\SFTPKeys\\Bank\\id_rsa", clientValue: "Location of your security key file on your computer" },
      { field: "Download Path", value: "Folder where downloaded statement files are saved", clientValue: "The folder on your PC where statement files will be stored" },
      { field: "Archive Path", value: "Folder where processed statement files are archived", clientValue: "A folder where processed statements are kept for reference" },
    ],
    notes: "Tip: Host IP and Username must be unique — you cannot duplicate these across bank setups.",
  },
  {
    id: 6, type: "keyfile",
    title: "SFTP with Key File: Generating Keys",
    clientTitle: "Setting Up a Security Key File",
    steps: [
      { step: "1", label: "Open Windows Command Prompt (Windows key > type cmd > Enter)" },
      { step: "2", label: "Run: ssh-keygen -m PEM and press Enter" },
      { step: "3", label: "Enter a file path e.g. C:\\SFTPKeys\\JohnSmith\\id_rsa" },
      { step: "4", label: "Enter a passphrase (or press Enter to skip) and confirm" },
      { step: "5", label: "Two files created: id_rsa (keep private) and id_rsa.pub (share with bank)" },
      { step: "6", label: "Enter the id_rsa path in the Key File field in RecXpress SFTP setup" },
    ],
    clientSteps: [
      { step: "1", label: "Your consultant will generate a pair of security key files on your computer" },
      { step: "2", label: "The private key stays on your system and is never shared" },
      { step: "3", label: "The public key (.pub file) is sent to your bank for them to register" },
      { step: "4", label: "Once registered, RecXpress uses the key to authenticate automatically" },
      { step: "5", label: "No password is required — the key handles authentication securely" },
    ],
    warning: "Common error: using the wrong key file or wrong format. Always use ssh-keygen -m PEM.",
    clientNote: "Your bank will confirm when the key is registered and the connection is ready to test.",
    notes: "The .pub file goes to the bank; the private key stays on your server.",
  },
  {
    id: 7, type: "bullets", icon: "🧪",
    title: "Testing Your SFTP Connection",
    clientTitle: "Making Sure Everything Works",
    points: [
      "Use the Test Connection button inside the RecXpress SFTP setup screen",
      "RecXpress will attempt to connect using your supplied settings",
      "Connection timeout is approximately 30 seconds if no connection is established",
      "Use View Log to open the SFTP log file (PSRXSecure.log)",
      "The log records all activities: connection attempts, file transfers, archive operations",
      "Check the log file first whenever a test connection fails",
    ],
    clientPoints: [
      "Once setup is complete, click Test Connection to verify everything is working",
      "A successful test confirms your credentials and server details are correct",
      "If the test fails, your consultant will check the connection log to diagnose the issue",
      "No go-live until the test passes — we make sure it works before relying on it",
    ],
    notes: "Always test before going live. The log file is the first place to look when troubleshooting.",
  },
  {
    id: 8, type: "rebex",
    title: "Testing Your RecXpress SFTP Setup",
    clientTitle: "We Test Before Connecting to Your Bank",
    intro: "RecXpress includes a built-in Test Connection button to verify your SFTP setup before going live. PSRXSecure.log records all activity for troubleshooting.",
    clientIntro: "Before connecting to your live bank, we run a full test to make sure everything is configured correctly.",
    steps: [
      { step: "1", label: "Open Bank Account setup > RecXpress tab in Sage 300 Cashbook" },
      { step: "2", label: "Enter all SFTP connection details (Host IP, User, Password or Key File)" },
      { step: "3", label: "Click the Test Connection button to attempt a live connection" },
      { step: "4", label: "Click View Log to open PSRXSecure.log and review the connection result" },
      { step: "5", label: "Resolve any errors shown in the log before proceeding" },
      { step: "6", label: "Once the test passes, confirm a statement file is retrieved successfully" },
    ],
    clientSteps: [
      { step: "1", label: "Your consultant enters the SFTP details provided by your bank" },
      { step: "2", label: "A test connection is run directly from RecXpress" },
      { step: "3", label: "The connection log confirms whether the setup is successful" },
      { step: "4", label: "Any issues are resolved before going live — no disruption to your workflow" },
    ],
    notes: "Always verify via the log file, not just the on-screen success message.",
  },
  {
    id: 9, type: "tips",
    title: "Key Tips and Common Errors",
    clientTitle: "What to Expect and Common Questions",
    tips: [
      { icon: "⚠️", label: "Unique credentials required", desc: "Cannot duplicate Host IP Address and Username across different bank setups.", clientDesc: "Each bank account needs its own separate SFTP credentials from your bank." },
      { icon: "🔍", label: "Wrong key file format", desc: "Most common Key File error. Always generate keys using ssh-keygen -m PEM.", clientDesc: "If using a key file, your consultant ensures it is generated in the correct format." },
      { icon: "🔐", label: "Incorrect password error", desc: "count must be non-negative typically means the password entered is incorrect.", clientDesc: "Double-check SFTP credentials with your bank if a connection error occurs." },
      { icon: "📋", label: "Always check the log", desc: "PSRXSecure.log records every SFTP activity — first stop for troubleshooting.", clientDesc: "A full activity log is kept, making any issues easy to diagnose." },
      { icon: "👤", label: "Separate user for Automation", desc: "Run RecXpress Automation under a separate Sage 300 login to avoid locking the session date.", clientDesc: "RecXpress Automation should run under its own Sage 300 user to avoid impacting other users." },
    ],
    notes: "These tips save significant support time — cover them before wrapping up.",
  },
  {
    id: 10, type: "checklist",
    title: "Setup Checklist",
    clientTitle: "Your Setup Journey",
    checklist: [
      "Confirm SFTP method with your bank (Password / Key File / 2FA)",
      "Obtain Host IP Address, Username and Password (or Key File) from your bank",
      "Generate SSH keys using ssh-keygen -m PEM if using Key File method",
      "Navigate to Bank Account > RecXpress tab in Sage 300 Cashbook",
      "Enter SFTP connection details and set Download / Archive paths",
      "Click Test Connection and verify result via View Log",
      "Confirm successful file retrieval before going live",
    ],
    clientChecklist: [
      "Contact your bank to request SFTP access and credentials",
      "Share credentials securely with your Sage 300 consultant",
      "Consultant configures RecXpress with your bank details",
      "Test connection is run and confirmed successful",
      "First automatic statement retrieval is verified",
      "You are live — statements import automatically from now on",
    ],
    notes: "Leave this slide up during Q&A. A ready-to-use checklist partners can follow with their clients.",
  },
];
